### ISSUE TITLE
Slightly over 10k

### ISSUE THREAD

**Issue by aarongustafson** [michaeltrilford/michaeltrilford.github.io#1]
I get 10.2k. I will publish as-is which will get you "update"-ability, but recommend a tiny bit of shaving ;-)

![screen shot 2016-09-20 at 11 24 13 am](https://cloud.githubusercontent.com/assets/75736/18676821/e62fd8bc-7f24-11e6-8e69-f18d0ed9ff8d.png)

**Comment by michaeltrilford** [comment]
Hey mate,

Hmm, maybe the it's the Azure setup? If you don't mind, are you able to
check the DL size on the https://michaeltrilford.github.io/ just to see if
you get 10.2k on there?

I had a feeling it might change based on the new host, I will see what I
can do to shave it.

Thanks

**Comment by michaeltrilford** [comment]
OK, that's fine. I can replicate here.

**Comment by michaeltrilford** [comment]
Hey Aaron,

I have made some slight tweaks, hoping that can get me over the finish line.

I'm clicking on the super secret link, but I'm getting this message
"Sorry... Your project is not published yet so we cannot update the
content, please try again later"

I'm assuming Azure is link to my Github repo and it will update it due
time? Once it has been published, I can double check the initial DL for
more tweaks.

Thanks

**Comment by aarongustafson** [comment]
You should be good now. And well under the 10k :-)

**Comment by michaeltrilford** [comment]
Oh great! I made minor changes really, a good chance to sift through the
CSS and consolidate something I missed.

Cheers mate.

**Comment by michaeltrilford** [comment]
Hey Aaron,

I'm trying to see the updated version at this link:
https://tips-for-your-first-10k-b-10kapart2016.azurewebsites.net/

But it hasn't been refreshed yet, do I need to do anything?

Mike.

**Comment by aarongustafson** [comment]
Check now. I was pushing new stuff and hadn’t gotten back to the update
queue.
